### ISSUE TITLE
Blindnet responsiveness

### ISSUE THREAD

**Issue by tibastral** [blindnet-io/product-management#956] opened 2022-09-20 14:24 UTC
<img width="1329" alt="Screenshot 2022-09-16 at 14 24 51" src="https://user-images.githubusercontent.com/33167/191283742-daca8997-45cf-4e4d-b18b-00696dea968b.png">

Hey, I don't understand why the content of the app is overlapped by the menu (on the left), and why it doesn't work on mobile. Could you explain please ? Thank you (https://www.perficient.com/insights/research-hub/mobile-vs-desktop-usage)

**Comment by noelmace** [comment] 2022-09-21 16:10
There are indeed two important issues here:
1. Storybook (the product we use to showcase the Privacy Components for the Web) isn't configured to take the menu width into account when defining the content's width.
2. The PRCI and DCI web components have been initially developed in a non-responsive way for demonstration purposes. Rewriting of the styles for progressiveness is in progress (ping @jboileau99 for more details if needed)

Thank you for this feedback. We have defined a higher priority for those issues and will keep you posted here.

**Comment by noelmace** [comment] 2022-09-22 12:17
The first issue ("the content of the app is overlapped by the menu") should be solved by https://github.com/blindnet-io/privacy-components-web/pull/152 in the next release of [Privacy Components for the Web](https://github.com/blindnet-io/privacy-components-web).

The more advanced one ("it doesn't work on mobile") is progressively addressed while building the next version, but will be really covered by https://github.com/blindnet-io/privacy-components-web/issues/153.

Styles are defined in each component via the `static styles` property using lit `css` tagged template literals (cf. [lit.dev > styling](https://lit.dev/docs/components/styles/). Example: https://github.com/blindnet-io/privacy-components-web/blob/develop/packages/prci/src/BldnPrivRequest.ts#L40-L88. I'll be happy to support you at every step if you wanna make a contribution to help us fix this issue.

**Comment by noelmace** [comment] 2022-10-07 21:57
Closing as a duplicate of https://github.com/blindnet-io/privacy-components-web/pull/152 and https://github.com/blindnet-io/privacy-components-web/issues/153.

**Closed by noelmace** 2022-10-07 21:57 UTC
Labels: type: bug
