### ISSUE TITLE
Remove plaintext emails from the database

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#524] opened 2022-04-14 10:17 UTC
Goal: remove plaintext emails from the `SubmittedForms` and `PatientsRequests` tables.

Prerequisites:

- Send GDPR delete confirmation emails without using emails from the db (encode emails in the URLs).
- Match submitted forms with GDPR submitter by using hashed email instead of plaintext email.

**Comment by loncarb** [comment] 2022-07-26 10:32
@Clementinev @m4rk055 @noelmace We have problems here, if we remove email column from `PatientsRequests` tabel we will not be able to send email to data submitter that their gdpr request is approved/rejected/partially approved and confirm delete request.

But we can remove `email` from `SubmittedForms` table

**Comment by m4rk055** [comment] 2022-07-26 11:29
Data subject's email address is encrypted in the GDPR request.
When the request is resolved client side, send that email address in plaintext to the server, send an email message to the data subject and "forget" the email address.

**Comment by nikolaFusion** [comment] 2022-07-28 10:20
@Clementinev @noelmace We have problem when data submitter when he is trying to confirm his delete request by clicking URL from email. We don't have his email there. What we can do is add email in the URL, but in some previous task  you asked to remove email from URL?

**Comment by Clementinev** [comment] 2022-08-02 09:11
https://github.com/blindnet-io/product-management/issues/349

**Comment by noelmace** [comment] 2022-08-02 09:16
I don't think #349 should impact how you address this specific issue.
I think you can directly include the email address in the URL in the email, or our a specific uuid for the request if it doesn't require to store the email address.

@m4rk055 could you please quickly give your 2 cents on this? Thx

**Comment by Clementinev** [comment] 2022-08-02 09:24
Does it have an impact on the user experience/UI that I should test ? (for example has the url changed ?)

**Comment by loncarb** [comment] 2022-08-02 10:05
@noelmace @Clementinev we changed URL before it was 
`baseUrl/gdpr/{requestId}/token/{token}` and now it is
`baseUrl/gdpr/{requestId}/token/{token}/email/{emailBase64}`

so we just didn't put plain email but base64 of it

**Comment by noelmace** [comment] 2022-08-02 10:13
Ok, thx @loncarb.
I'd still like to ensure everything is OK with @blindnet-io/engineering here.
So I'll move this to v1.0.10 to give them time to (**very quickly**) review this, give feedback if needed, and then for you to make the required changes accordingly.
As the current changes don't seem to introduce any regression (ping @Clementinev), I'm ok with including in v1.0.9 what's already done if you can't do otherwise.

Please just give us the reference of the related PRs and commits as a comment below.
I'll directly discuss this with @blindnet-io/engineering myself, no need for you to interact their time.

**Comment by loncarb** [comment] 2022-08-02 10:48
this is PR https://github.com/blindnet-io/privateform-server/pull/41/files
but here you will see a lot of files since we removed fields from DB.

It's all done so if you are ok with base64 as email I'll keep this in `v1.0.9`, if @Clementinev doesn't find any bugs

**Comment by Clementinev** [comment] 2022-08-02 11:34
> we changed URL before it was `baseUrl/gdpr/{requestId}/token/{token}` and now it is `baseUrl/gdpr/{requestId}/token/{token}/email/{emailBase64}`
> 
> so we just didn't put plain email but base64 of it

This is fine for it doesn't show plain text email

Is there a way to shorten the URL as it is quite long ?

**Comment by m4rk055** [comment] 2022-08-02 11:46
I think a better solution would be to temporarily store the email address in the db, and delete it once the email message is sent.
If we keep it in the URL, a user can change it. Don't know if that's a security concern in this case, if not, it's definitely a more "convenient solution".

@Clementinev From the UX standpoint, do we really need to send the second email after the delete request is confirmed?

**Comment by Clementinev** [comment] 2022-08-02 11:50
Yes it is needed to confirm their action, and send them the link to follow the status of their request

**Comment by Clementinev** [comment] 2022-08-05 13:39
Make sure it is encoded with base64url before we close it

**Comment by loncarb** [comment] 2022-08-09 12:00
@Clementinev it is

**Closed** 2022-08-10 11:53 UTC
