### ISSUE TITLE
✨ [PCE] custom DAC instance

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#983] opened 2022-10-13 13:54 UTC
### Which blindnet product(s) are relevant/related to the feature/enhancement request?

(DevKit) Privacy Computation Engine

### Does it seem to be a simple enhancement of an existing feature?

Yes

### Description

Running the DevKit on-premise requires to set-up instance URLs so each component can communicate with the others.
Currently, the PCE doesn't allow to set-up the URL of a DAC instance.

> **Note**
>
> This feature is required to finalise the introductory tutorial (cf. https://github.com/blindnet-io/blindnet.dev/pull/71).

### Proposed solution

Environment variable.

### Alternatives considered

New dedicated `technical` configuration API endpoint

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by noelmace** [comment] 2022-10-13 13:55
As @m4rk055 is on vacation, I'm trying to identify how to do this despite my beginner level in Scala.
Help and advice are highly welcomed (ping @TheKinrar).

**Comment by TheKinrar** [comment] 2022-10-13 19:11
Depends on how you're currently creating the app in the PCE database.

I see there are a few SQL scripts around in the repo, with lines like these:
```sql
insert into apps values ('6f083c15-4ada-4671-a6d1-c671bc9105dc');

insert into dac values ('6f083c15-4ada-4671-a6d1-c671bc9105dc', true, 'https://test');
```

So you can easily replace the DAC url at the end of the second query.

When auth and multi-app support are merged (https://github.com/blindnet-io/privacy-computation-engine/pull/20), we should be able to easily implement a more future-proof solution obviously.

**Comment by noelmace** [comment] 2022-10-14 10:01
I don't think we can afford to ask 3rd party devs to directly edit the DB in the tutorial.
I still can't find where the URL is actually defined. I found https://github.com/blindnet-io/privacy-computation-engine/blob/develop/modules/core/src/main/scala/model/PCEApp.scala#L28, but that's it. It would take me several days to actually do this PR, while @m4rk055 will be able to do that in a few minutes I think :sweat_smile: So I'll focus on more effective actions from there, and we can discuss this on monday.

**Comment by TheKinrar** [comment] 2022-10-14 10:06
It's in the DB. There's no point in asking for the endpoint to be made now, because it is a per-app setting, and therefore relies on per-app configuration. This part is almost done but me and @m4rk055 need to coordinate on this, which is why I was talking about waiting for https://github.com/blindnet-io/privacy-computation-engine/pull/20 to be merged.

I also don't think we can afford to ask 3rd party devs to use any SQL scripts in a tutorial I would say, PCE should be able to self-initialize on first startup (and from what I can see in the source code, it's meant to be this way)

**Comment by TheKinrar** [comment] 2022-10-14 10:09
To me the issue is that we're writing tutorials for completely WIP components, and there obviously are some missing parts. As soon as configuration is ready, we'll be able to complete the tutorial. (Which means, during next week.)

There's an identity server planned, which is supposed to be at the core of any devkit deployment, and the tutorial doesn't talk about it yet: that's another example of a blind spot from the docs that we should be able to fix in a week or two.

**Closed** 2022-12-19 11:47 UTC
Labels: type: feature
