### ISSUE TITLE
Bug when opening data request from email - Privateform

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#736] opened 2022-06-30 08:01 UTC
When I try to open a data request from the reminder email :
<img width="600" alt="Screenshot 2022-06-30 at 09 57 50" src="https://user-images.githubusercontent.com/89908145/176624483-0941dfd4-bc9e-4ac8-9b11-f805dc3f7a3c.png">

**-> I get the following error message** (it used to work well) : 
<img width="1440" alt="Screenshot 2022-06-30 at 09 39 00" src="https://user-images.githubusercontent.com/89908145/176624516-e8fb8553-dba5-492f-b54c-8e4c91b290e0.png">

(I tried to refresh, delete cache, and also to open data request from other mail and it doesn't work)

**Comment by nikolaFusion** [comment] 2022-08-15 10:24
@Clementinev   This problem is old. We cant to reproduce this bug. With us everything works fine.

**Comment by noelmace** [comment] 2022-08-16 08:51
I can't reproduce either, so I'm closing it. @Clementinev please reopen and add details when you're back if you can reproduce.

**Closed by noelmace** 2022-08-16 08:51 UTC
Labels: type: bug, env: staging, priority: 2 (required)
