### ISSUE TITLE
[Epic]: Finish Scoping blindnet devkit for Q3 2022 milestone

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#752] opened 2022-07-01 19:46 UTC
In order to start building finish-up pending decisions regarding to blindnet devkit scope that will go in the Q3 2022 version of the product, finish the architecture documents, models and first version of PRIV.

## Subtasks

- [ ] #742 
- [ ] #751 
- [ ] #659 
- [ ] #723 
- [ ] #748 
- [ ] #754

## Prerequsite

This goal can only be achieved once we have all mastered the **Antiperfectionism principle**: _(Good-enough, finished) is prefered over (Potentially perfect, in progress)._

**Comment by noelmace** [comment] 2022-07-05 22:40
Duplicate of #760 (which has been clarified with @m4rk055 and @TheKinrar).

**Closed by noelmace** 2022-07-05 22:40 UTC
Labels: priority: 0 (critical), help wanted
