### ISSUE TITLE
Reproduce duplicated db entries 

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#244] opened 2021-09-29 15:38 UTC
See #228 

Make two database entries with the same email. As a result of that, a user with the given email is not confirmed nor is able to register an account again, and is locked out of PrivateForm.

**Comment by loncarb** [comment] 2022-08-01 07:03
This ticket is old did someone managed to reproduce this?

**Comment by loncarb** [comment] 2022-08-12 14:21
We couldn't reproduce this so I will close it.

**Closed** 2022-08-12 14:21 UTC
Labels: type: bug, priority: 1 (urgent), effort1: easy (hours)
